# Generated by Django 3.2.8 on 2021-11-21 07:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_videocloudinary_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocloudinary',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
