# Generated by Django 3.2.8 on 2021-11-30 12:06

import cloudinary.models
import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0006_alter_videocloudinary_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocloudinary',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.CreateModel(
            name='TestModelWithVideoAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.ImageField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video])),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('is_estimated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
