# Generated by Django 3.2.8 on 2021-11-30 12:26

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20211130_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodelwithvideoandimage',
            name='video_file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
