# Generated by Django 3.2.8 on 2021-12-02 07:14

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_testmodelwithvideoandimage_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocloudinary',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videocloudinary',
            name='video_file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=video.models.user_directory_path, validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.DeleteModel(
            name='TestModelWithVideoAndImage',
        ),
    ]
