# Generated by Django 3.2.8 on 2021-12-14 03:14

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20211202_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocloudinary',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=video.models.user_directory_path, validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
