# Generated by Django 3.2.8 on 2021-12-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_videocloudinary_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocloudinary',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
